#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# source files in this project (main.cpp is automatically assumed)
SOURCES :=

# header files in this project
HEADERS := Button.hpp ButtonListener.hpp BuzzerControl.hpp DisplayControl.hpp GameLogs.hpp IRControl.hpp Keypad.hpp KeypadControl.hpp MsgDecoder.hpp MsgListener.hpp PauseDetector.hpp PauseListener.hpp PlayerControl.hpp PlayerData.hpp ShootControl.hpp Weapon.hpp

# other places to look for files for this project
SEARCH  :=

# set REATIVE to the next higher directory 
# and defer to the Makefile.due there
RELATIVE := $(RELATIVE)../
include $(RELATIVE)Makefile.due